import type { Metadata } from "next";

import "./globals.css";
import { Open_Sans, Gilda_Display } from "next/font/google";


const openSans = Open_Sans({
  subsets: ["latin"],
  display: 'swap',
  variable: '--font-open-sans',
});

const gildaDisplay = Gilda_Display({
  weight: ['400'],
  subsets: ["latin"],
  display: 'swap',
  variable: '--font-gilda-display',
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${openSans.variable} ${gildaDisplay.variable} antialiased`}>
      
      <body>
      
        {children}
        
      </body>
    </html>
  );
}
