import type { Metadata } from "next";
import { Open_Sans, Gilda_Display } from "next/font/google";
import "./globals.css";
import { SanityLive } from "../sanity/lib/live";

const openSans = Open_Sans({
  subsets: ["latin"],
  variable: '--font-open-sans',
});

const gildaDisplay = Gilda_Display({
  weight: ["400"],
  subsets: ["latin"],
  variable: '--font-gilda-display',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body className={`${openSans.variable} ${gildaDisplay.variable} font-sans`}>
      
        {children}
        <SanityLive />
      </body>
    </html>
  );
}
