import type { Metadata } from "next";
import Link from "next/link";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <nav>
      

      <Link href="/" className="text-3xl text-blue-500 hover:underline"> Home</Link>
      <Link href="/projects" className="text-3xl text-blue-500 hover:underline"> Projects</Link>
      <Link href="/about" className="text-3xl text-blue-500 hover:underline"> About</Link>
      <Link href="/reviews" className="text-3xl text-blue-500 hover:underline"> Reviews</Link>
      <Link href="/contact" className="text-3xl text-blue-500 hover:underline"> Contact</Link>
        {children}


    </nav>
  );
}
