
import type { Metadata } from "next";
import { SanityLive } from "@/sanity/lib/live";
import { sanityFetch } from "../../sanity/lib/live";
import { QUERY_LOGO } from './queries/logoQuery';
import { QUERY_NAV } from './queries/navQuery';
import { Navigation } from './components/Navigation';
import type { LogoType, NavLabelsType, SanityImageObject } from '../types'
import { DebugProvider } from './context/DebugContext'
import { DebugKeyboardProvider } from './components/providers/DebugKeyboardProvider'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const { data: logo } = await sanityFetch({ query: QUERY_LOGO });
  const { data: navData } = await sanityFetch({ query: QUERY_NAV });


if (!logo || !navData) {
  return <div>A logo or menu labels are missing. Please check Sanity content.</div>;
}


  return (
    <DebugProvider>
      <DebugKeyboardProvider>
      <Navigation
        logo={logo as LogoType}
        navLabels={navData as NavLabelsType}
        mobileBackgroundImage={navData.mobileBackgroundImage as SanityImageObject | undefined}
      />
          
          {children}

          <SanityLive />
        </DebugKeyboardProvider>
    </DebugProvider>
  );
}
