import type { Metadata } from "next";
import { SanityLive } from "@/sanity/lib/live";
import { defineQuery } from "next-sanity";
import { sanityFetch } from "../../sanity/lib/live";
import { QUERY_LOGO } from './queries/QUERY_LOGO';
import { Navigation } from './components/Navigation';
import type { LogoType, NavLabelsType, MobileBackgroundImageType } from '../types'

const QUERY_NAV = defineQuery(`*[_type == "siteSettingsSingleton"][0]{
  homePageNavLabel,
  projectsPageNavLabel,
  aboutPageNavLabel,
  reviewsPageNavLabel,
  contactPageNavLabel,
  mobileBackgroundImage {
    ...,
    asset->{
      ...,
      metadata
    }
  }
}`);

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const { data: logo } = await sanityFetch({ query: QUERY_LOGO });
  const { data: navData } = await sanityFetch({ query: QUERY_NAV });

if (!logo || !navData) {
  return <div>A logo or menu labels are missing. Please check Sanity content.</div>;
}


  return (
    <>
    
      <Navigation
        logo={logo as LogoType}
        navLabels={navData as NavLabelsType}
        mobileBackgroundImage={navData.mobileBackgroundImage  as MobileBackgroundImageType | undefined}
      />
        
        {children}

        <SanityLive />
    </>
  );
}
